### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by mkaraniya** [indianbhaiya/IndianBot#8]
those who are using it are under a big security problem.

**Comment by indianbhaiya** [comment]
what btw!

**Comment by xditya** [comment]
@mkaraniya What?

**Comment by midhunkm1294-bit** [comment]
Guys! There Is Nothing Like That 😎
The Telegram Accepts This Type Of bots
And it does not Violent Heroku Term And Conditions
You Are 100℅ Percent Safe ☺

We Can't Hack You With The deatails Which You Give To Userbot 

We Create Userbot For Helping You Managing You Telegram Account Efficiently 
- Thank You Regards, 
IndianBotTeam 
Jai Hindh!🇮🇳🇮🇳

**Comment by midhunkm1294-bit** [comment]
If You Have AnyProblem Don't hesitate To Ask Help 
Ask At - @indianBot_Official -In Telegram 
🙏

**Comment by indianbhaiya** [comment]
bro tell what was the issue as said by u

**Comment by amitkr-codes** [comment]
@mkaraniya can you pls elaborate this security issue
